// Copyright (c) 2020. BMS Circuits

/// This class provides a set of [bool] helpers, not provided by Dart.
///
/// String parsing methods
/// ----------------------
///
/// Others basic types feature both
/// - a toString function which encodes a value as a String
/// - a parse/tryParse pair which decodes the string into a value
///
/// Unfortunately Dart [bool] only features a toString at the time of writing.
/// This helper provides those two missing functions.
///
/// Extending [bool] type
/// ---------------------
///
/// Extending bool type (to inject parse functions in it for example)
/// is unfortunately prohibited by Dart.
class BoolHelper {
  /// BoolHelper is a set of static function helpers,
  /// nobody can instanciate it.
  _BoolHelper() {}

  /// Parse [source] as a [bool].
  ///
  /// The [source] is expected to be either "true" or "false", whichever case
  /// (upper, lower or mixed case). It must not be null.
  ///
  /// This method is compatible with [bool.toString] since it recognize strings
  /// generated by [bool.toString] (and a few more).
  ///
  /// If the [source] string does not contain a valid boolean literal,
  /// a [FormatException] is thrown.
  ///
  /// See also [tryParse].
  static bool parse(String source) {
    final String sourceLower = source.toLowerCase();

    if (sourceLower == "true") {
      return true;
    }
    if (sourceLower == "false") {
      return false;
    }

    throw FormatException("Literal does not describe a boolean", source);
  }

  /// Parse [source] as a [bool].
  ///
  /// The [source] is expected to be either "true" or "false", whichever case
  /// (upper, lower or mixed case). It must not be null.
  ///
  /// This method is compatible with [bool.toString] since it recognize strings
  /// generated by [bool.toString] (and a few more).
  ///
  /// If the [source] string does not contain a valid boolean literal,
  /// null is returned.
  ///
  /// See also [parse].
  static bool tryParse(String source) {
    try {
      return parse(source);
    } on FormatException {
      return null;
    }
  }
}
