# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

sdk:
  - stable

stages:
  - analyze:
      - group:
          - analyze: --fatal-infos .
          - command:
              - dart pub global activate pana
              # TODO(brolandeau): Add `--exit-code-threshold 20` when the issue:
              # https://github.com/dart-lang/pana/issues/1020, is fixed.
              - pana --line-length 100 .
  - unit_test:
      - test: --flavor test .
