include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/intl/**
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - camel_case_types
    - always_declare_return_types
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - hash_and_equals
    - throw_in_finally
    - use_key_in_widget_constructors
    - valid_regexps
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_init_to_null
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_constructor_bodies
    - file_names
    - flutter_style_todos
    - implementation_imports
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_is_even_rather_than_modulo
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_to_and_as_if_applicable
    - void_checks
