# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

sdk:
  - stable

stages:
  - analyze:
      - group:
          - analyze: --fatal-infos .
  - unit_test:
      - test: --flavor test .
